version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Abcd1234
    restart: always   
  # dynamodb:
  #   image: instructure/dynamo-local-admin
  #   ports:
  #    - "8000:8000"
  #    - "8001:8001"
  #   restart: always
  
  # node-gateway:
  #   build:
  #     args:
  #       - EXPOSE_PORT=80
  #     context: /home/ubuntu/resources/node
  #   ports:
  #    - "80:80"
  #   environment:
  #    - HOSTNAME=gateway
  #    - SOA_PATH=/usr/src/dist/gateway.js
  #    - PORT=80
  #    - MQ_PROTOCOL=amqp
  #    - MQ_HOSTNAME=rabbitmq
  #    - MQ_PORT=5672
  #    - MQ_USERNAME=admin
  #    - MQ_PASSWORD=Abcd1234
  #   restart: on-failure
  #   depends_on:
  #    - rabbitmq
  #   volumes:
  #    - /home/ubuntu/resources/node/:/usr/src/app

  # node-service-auth:
  #   build:
  #     args:
  #      - EXPOSE_PORT=3131
  #     context: /home/ubuntu/resources/node
  #   ports:
  #     - "3131:3131"
  #   environment:
  #     - HOSTNAME=auth
  #     - SOA_PATH=/usr/src/dist/auth/service.js
  #     - AUTHENTICATION_SECRET=secretFake
  #     - MQ_PROTOCOL=amqp
  #     - MQ_HOSTNAME=rabbitmq
  #     - MQ_PORT=5672
  #     - MQ_USERNAME=admin
  #     - MQ_PASSWORD=Abcd1234
  #     - MQ_QUEUE=auth
  #     - AWS_REGION=us-east-1
  #     - DYNAMODB_URL=http://dynamodb:8000
  #     - DYNAMODB_ACCESS_KEY=fakeKey
  #     - DYNAMODB_ACCESS_SECRET=fakeSecret
  #   restart: on-failure
  #   depends_on:
  #     - dynamodb
  #     - rabbitmq
  #   volumes:
  #     - /home/ubuntu/resources/node:/usr/src/app
  
  elixir-gateway:
    build:
      context: /home/ubuntu/resources/elixir
    ports:
     - "80:80"
    environment:
    - GATEWAY_ENV=local
    - HOSTNAME=gateway
    - PORT=80
    - MQ_PROTOCOL=amqp
    - MQ_HOSTNAME=rabbitmq
    - MQ_PORT=5672
    - MQ_USERNAME=admin
    - MQ_PASSWORD=Abcd1234
    - MQ_QUEUE=gateway
    depends_on:
     - rabbitmq
    restart: on-failure
    volumes:
      - /home/ubuntu/resources/elixir/gateway/lib:/usr/src/app/lib/
  
  # elixir-auth:
  #   build:
  #     args:
  #      - EXPOSE_PORT=3232
  #     context: /home/ubuntu/resources/elixir/service
  #   ports:
  #     - "3232:3232"
  #   environment:
  #     - SERVICE_ENV=local
  #     - HOSTNAME=auth
  #     - PORT=3232
  #     - AUTHENTICATION_SECRET=2af0ba9d-78d3-429b-a7f6-8ac973598d2
  #     - MQ_PROTOCOL=amqp
  #     - MQ_HOSTNAME=rabbitmq
  #     - MQ_PORT=5672
  #     - MQ_USERNAME=admin
  #     - MQ_PASSWORD=Abcd1234
  #     - MQ_QUEUE=auth
  #     - AWS_REGION=us-east-1
  #     - DYNAMODB_URL=http://dynamodb:8000
  #     - DYNAMODB_ACCESS_KEY=fakeKey
  #     - DYNAMODB_ACCESS_SECRET=fakeSecret
  #   depends_on:
  #     - rabbitmq
  #     - dynamodb
  #   restart: on-failure
  #   volumes:
  #     - /home/ubuntu/resources/elixir/services/auth:/usr/src/app/